### ISSUE TITLE
Build fails - Missing required Modules

### ISSUE THREAD

**Issue by ghost** [KinveyApps/iOS-Starter#1]
I'm getting the following errors when I try to build the project.

`/Users/Ian/Desktop/IOS-Starter-master/Bookshelf/Book.swift:10:8: Missing required modules: 'KinveyKit', 'MongoDBPredicateAdaptor'`

I've downloaded the ZIP, extracted and then run "pod install" on the directory to ensure all the required libraries are present.

Should there be some mode entries in the pod file?

**Comment by heyzooi** [comment]
please try again. it should be now fixed.

**Comment by ghost** [comment]
I ended up adding the components manually - and all is fine.

**Comment by heyzooi** [comment]
cool, thanks for your patience!
